name: Update Standings

on:
  schedule:
    - cron: "*/15 * * * *" #Done every 15 minutes
  workflow_dispatch:

permissions:
  contents: write # Allows for github-actions[bot] to push code

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # ensures the token is kept

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add baseballtier1standings.json
          git commit -m "Update standings" || echo "No changes to commit"
          git push
