name: Update Baseball Tier 1 Standings

on:
  schedule:
    - cron: "*/15 * * * *" # does process every 15 minutes
  workflow_dispatch: # allow manual run too

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add baseballtier1standings.json
          git commit -m "Update standings" || echo "No changes to commit"
          git push
